### PR TITLE
feat: add unit tests to SearchServiceTests

### LINKED ISSUE #407: Add more unit test coverage to Search package
#396 did a great job of getting things started, however we should expand on this and add more test coverage

### PR DESCRIPTION
**Pull request by alter-kaker**
- add testSearchPostByUrlReturnsEmptyWhenNoPosts - fails, disabled 
- add testSearchPostByUrlWithCrossPostsFewerPostsThanPageSize - fails, disabled 
- add testSearchPostByUrlWithCrossPostsOnePageWorthOfPostsRequestSecondPage - fails, disabled 
- rename testSearchPostByUrlWithCrossPostsReturnsExactlyOnePageWorthOfResults - passes 
- add testSearchPostByUrlWithCrossPostsPageOneOfTwo - passes 
- add testSearchPostByUrlWithCrossPostsPageTwoOfTwo - passes

closes #407

### CODE REVIEW

**Review by lazyguru — APPROVED** [review]
My only comment here would be that it would probably be better to move some of the repeated blocks of code into either a setup() call or have a separate function you could call to configure the tests where you reuse that same block of code. Otherwise, thanks for the contribution! I'm going to leave the PR unmerged for 1 day to allow @jgrim or @Pdzly to weigh in if they want

**Comment by lazyguru** [comment]
Also, @alter-kaker would you be able to configure your git client to [sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) your commits?

**Review by Pdzly — APPROVED** [review]

**Comment by lazyguru** [comment]
@alter-kaker please [sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) your commits

**Comment by lazyguru** [comment]
I'm closing this PR as there has been no response to my requests for the commits to be signed. When/if you are able to sign your commits, please feel free to reopen

**Pull request closed without merging**
