### PR TITLE
enable updates to updatedAt field

### PR DESCRIPTION
**Pull request by rohit-satya**
Close https://github.com/sublinks/sublinks-api/issues/373

### CODE REVIEW

**Review by jgrim — CHANGES_REQUESTED** [review]
The field should be immutable. The issue is that something is trying to change it.

**Comment by rohit-satya** [comment]
Please share complete StackTrace

**Comment by lazyguru** [comment]
I don't have a stack trace. All I have is the log message I posted in the issue. You should be able to reproduce this by running the docker setup. When the seeder triggers and starts creating entities you will see the message appear spread out through the calls. It seems like something triggers an update to the slur filter when a user or post (or comment? I didn't actually look to see what was being done at the time. Will do better on that next time I open an issue based on logs). I would expect the slur filter to only be updated when an admin takes action on it in the UI.

**Comment by Pdzly** [comment]
@rohit-satya see #383 

It was an issue with the switching over to postgresql, as the @UpdatedTimestamp always updates the attribute but it shouldnt? and it needs to be nullable.

**Pull request closed without merging**
